baseURL = "https://emielvanliere.github.io/emielvanliere.github.io"
headerFontSize = 128
languageCode = "en-us"
publishDir = "docs"
theme = "skeletron"
title = "emielvanliere.github.io"
[github]
	owner_name = "emielvanliere"
	repository_name = "emielvanliere.github.io"
[menu]
	[[menu.footer]]
		identifier = "about"
		name = "About"
		url = "/about/"
	[[menu.footer]]
		identifier = "manual"
		name = "Manual"
		url = "/manual"
[params]
	project_name = "Skeletron"
